// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// KMeans
List KMeans(NumericMatrix X, unsigned int k, unsigned int iter, unsigned int m, bool verbose, bool allmodels);
RcppExport SEXP yakmoR_KMeans(SEXP XSEXP, SEXP kSEXP, SEXP iterSEXP, SEXP mSEXP, SEXP verboseSEXP, SEXP allmodelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type k(kSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type allmodels(allmodelsSEXP);
    __result = Rcpp::wrap(KMeans(X, k, iter, m, verbose, allmodels));
    return __result;
END_RCPP
}
