# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  kmeans using yakmo
#' 
#'  @param	X		data matrix 
#'  @param	k		number of clusters
#'  @param	verbose		verbose output?
#'
NULL

KMeans <- function(X, k = 3L, iter = 100L, m = 1L, verbose = FALSE) {
    .Call('yakmoR_KMeans', PACKAGE = 'yakmoR', X, k, iter, m, verbose)
}

