# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  kmeans using yakmo
#' 
#'  @param	X		data matrix 
#'  @param	k		number of clusters
#'  @param	verbose		verbose output?
#'
#'
kmeans <- function(X, k, verbose = FALSE) {
    .Call('yakmoR_kmeans', PACKAGE = 'yakmoR', X, k, verbose)
}

